services:
  webots:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEBOTS_DEFAULT_IMAGE="cyberbotics/webots.cloud:R2025a-ubuntu22.04"
        - PROJECT_PATH="/usr/local/webots"
        - MAKE="make"
    command: $WEBOTS
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    environment:
      - DISPLAY=:0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "2000:2000"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /dev/dri:/dev/dri:rw
    networks:
      - logus2k_network      

networks:
  logus2k_network:
    external: true
